/* // var navLinks = document.getElementById("navLinks");

// function showMenu() {
//     navLinks.style.right = "0";
// }

// function hideMenu() {
//     navLinks.style.right = "-200px";
// }

// var herobtn = document.getElementById("hero-btn");

/* $(document).ready(function() {
    alert("hello world")
}); */

/* $(function() {
    $(".close-btn").click(function() {
        $(".menu").toggleClass("menu-open");
        $(this).toggleClass("open-btn");
    });
});

$('ul#father>li').hover(function() {
    $(this).find('ul#son').show(400);
}, function() {
    $(this).find('ul#son').hide(400);
}); */


// Vanilla Javascript: JS with no libarary or framework.

// <div id="now" class="card cards" >

/* var now = document.getElementById("now");

function removeNowElement() {
    now.remove();
};

removeNowElement();




function slideMenuRight() {

    // Array
    const menuElements = document.getElementsByClassName("menu");

    // Array access
    const firstMenuElement = menuElements[0];

    firstMenuElement.style.left = '-100px';
}

function setUpCloseButton() {
    const closebtn = document.getElementById("closebtn");

    closebtn.addEventListener('click', slideMenuRight);
};

setUpCloseButton(); */